POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "testadmin3",
  "password": "test3",
  "firstName": "Test",
  "lastName": "Admin",
  "email": "test3@test.com",
  "status": "admin"
}